# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1255587693);
user_pref("app.update.lastUpdateTime.background-update-timer", 1255587692);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1255587692);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1255587693);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1255587709);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1255587694);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.5pre");
user_pref("browser.tabs.autoHide", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.enabledItems", "langpack-en-GB@xulrunner-1.9.1.ubuntu.com:1.9.1.2,langpack-en-GB@firefox-3.5.ubuntu.com:3.5.2,ubufox@ubuntu.com:0.8,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.5pre");
user_pref("extensions.lastAppVersion", "3.5.5pre");
user_pref("extensions.update.enabled", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1258179695);
user_pref("xpinstall.whitelist.required", false);
